name: Broadcast 'push to develop' event to our release-scripts repo
on:
  status

jobs:
  send_notification:
    name: Send notification
    runs-on: ubuntu-22.04
    steps:
      - name: Get sender
        run: |
          echo "${{ toJson(github.event) }}"